(function(){var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.checkStringArgs=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};
$jscomp.polyfill("String.prototype.repeat",function(a){return a?a:function(a){var b=$jscomp.checkStringArgs(this,null,"repeat");if(0>a||1342177279<a)throw new RangeError("Invalid count value");a|=0;for(var d="";a;)if(a&1&&(d+=b),a>>>=1)b+=b;return d}},"es6","es3");var COMPILED=!0,goog=goog||{};goog.global=this;goog.isDef=function(a){return void 0!==a};goog.isString=function(a){return"string"==typeof a};goog.isBoolean=function(a){return"boolean"==typeof a};
goog.isNumber=function(a){return"number"==typeof a};goog.exportPath_=function(a,b,c){a=a.split(".");c=c||goog.global;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&goog.isDef(b)?c[d]=b:c=c[d]&&c[d]!==Object.prototype[d]?c[d]:c[d]={}};
goog.define=function(a,b){if(!COMPILED){var c=goog.global.CLOSURE_UNCOMPILED_DEFINES,d=goog.global.CLOSURE_DEFINES;c&&void 0===c.nodeType&&Object.prototype.hasOwnProperty.call(c,a)?b=c[a]:d&&void 0===d.nodeType&&Object.prototype.hasOwnProperty.call(d,a)&&(b=d[a])}goog.exportPath_(a,b)};goog.DEBUG=!0;goog.LOCALE="en";goog.TRUSTED_SITE=!0;goog.STRICT_MODE_COMPATIBLE=!1;goog.DISALLOW_TEST_ONLY_CODE=COMPILED&&!goog.DEBUG;goog.ENABLE_CHROME_APP_SAFE_SCRIPT_LOADING=!1;
goog.provide=function(a){if(goog.isInModuleLoader_())throw Error("goog.provide cannot be used within a module.");if(!COMPILED&&goog.isProvided_(a))throw Error('Namespace "'+a+'" already declared.');goog.constructNamespace_(a)};goog.constructNamespace_=function(a,b){if(!COMPILED){delete goog.implicitNamespaces_[a];for(var c=a;(c=c.substring(0,c.lastIndexOf(".")))&&!goog.getObjectByName(c);)goog.implicitNamespaces_[c]=!0}goog.exportPath_(a,b)};
goog.getScriptNonce=function(){null===goog.cspNonce_&&(goog.cspNonce_=goog.getScriptNonce_(goog.global.document)||"");return goog.cspNonce_};goog.NONCE_PATTERN_=/^[\w+/_-]+[=]{0,2}$/;goog.cspNonce_=null;goog.getScriptNonce_=function(a){return(a=a.querySelector&&a.querySelector("script[nonce]"))&&(a=a.nonce||a.getAttribute("nonce"))&&goog.NONCE_PATTERN_.test(a)?a:null};goog.VALID_MODULE_RE_=/^[a-zA-Z_$][a-zA-Z0-9._$]*$/;
goog.module=function(a){if(!goog.isString(a)||!a||-1==a.search(goog.VALID_MODULE_RE_))throw Error("Invalid module identifier");if(!goog.isInGoogModuleLoader_())throw Error("Module "+a+" has been loaded incorrectly. Note, modules cannot be loaded as normal scripts. They require some kind of pre-processing step. You're likely trying to load a module via a script tag or as a part of a concatenated bundle without rewriting the module. For more info see: https://github.com/google/closure-library/wiki/goog.module:-an-ES6-module-like-alternative-to-goog.provide.");
if(goog.moduleLoaderState_.moduleName)throw Error("goog.module may only be called once per module.");goog.moduleLoaderState_.moduleName=a;if(!COMPILED){if(goog.isProvided_(a))throw Error('Namespace "'+a+'" already declared.');delete goog.implicitNamespaces_[a]}};goog.module.get=function(a){return goog.module.getInternal_(a)};
goog.module.getInternal_=function(a){if(!COMPILED){if(a in goog.loadedModules_)return goog.loadedModules_[a].exports;if(!goog.implicitNamespaces_[a])return a=goog.getObjectByName(a),null!=a?a:null}return null};goog.ModuleType={ES6:"es6",GOOG:"goog"};goog.moduleLoaderState_=null;goog.isInModuleLoader_=function(){return goog.isInGoogModuleLoader_()||goog.isInEs6ModuleLoader_()};goog.isInGoogModuleLoader_=function(){return!!goog.moduleLoaderState_&&goog.moduleLoaderState_.type==goog.ModuleType.GOOG};
goog.isInEs6ModuleLoader_=function(){if(goog.moduleLoaderState_&&goog.moduleLoaderState_.type==goog.ModuleType.ES6)return!0;var a=goog.global.$jscomp;return a?"function"!=typeof a.getCurrentModulePath?!1:!!a.getCurrentModulePath():!1};
goog.module.declareLegacyNamespace=function(){if(!COMPILED&&!goog.isInGoogModuleLoader_())throw Error("goog.module.declareLegacyNamespace must be called from within a goog.module");if(!COMPILED&&!goog.moduleLoaderState_.moduleName)throw Error("goog.module must be called prior to goog.module.declareLegacyNamespace.");goog.moduleLoaderState_.declareLegacyNamespace=!0};
goog.declareModuleId=function(a){if(!COMPILED){if(!goog.isInEs6ModuleLoader_())throw Error("goog.declareModuleId may only be called from within an ES6 module");if(goog.moduleLoaderState_&&goog.moduleLoaderState_.moduleName)throw Error("goog.declareModuleId may only be called once per module.");if(a in goog.loadedModules_)throw Error('Module with namespace "'+a+'" already exists.');}if(goog.moduleLoaderState_)goog.moduleLoaderState_.moduleName=a;else{var b=goog.global.$jscomp;if(!b||"function"!=typeof b.getCurrentModulePath)throw Error('Module with namespace "'+
a+'" has been loaded incorrectly.');b=b.require(b.getCurrentModulePath());goog.loadedModules_[a]={exports:b,type:goog.ModuleType.ES6,moduleId:a}}};goog.module.declareNamespace=goog.declareModuleId;goog.setTestOnly=function(a){if(goog.DISALLOW_TEST_ONLY_CODE)throw a=a||"",Error("Importing test-only code into non-debug environment"+(a?": "+a:"."));};goog.forwardDeclare=function(a){};
COMPILED||(goog.isProvided_=function(a){return a in goog.loadedModules_||!goog.implicitNamespaces_[a]&&goog.isDefAndNotNull(goog.getObjectByName(a))},goog.implicitNamespaces_={"goog.module":!0});goog.getObjectByName=function(a,b){a=a.split(".");b=b||goog.global;for(var c=0;c<a.length;c++)if(b=b[a[c]],!goog.isDefAndNotNull(b))return null;return b};goog.globalize=function(a,b){b=b||goog.global;for(var c in a)b[c]=a[c]};
goog.addDependency=function(a,b,c,d){!COMPILED&&goog.DEPENDENCIES_ENABLED&&goog.debugLoader_.addDependency(a,b,c,d)};goog.ENABLE_DEBUG_LOADER=!0;goog.logToConsole_=function(a){goog.global.console&&goog.global.console.error(a)};
goog.require=function(a){if(!COMPILED){goog.ENABLE_DEBUG_LOADER&&goog.debugLoader_.requested(a);if(goog.isProvided_(a)){if(goog.isInModuleLoader_())return goog.module.getInternal_(a)}else if(goog.ENABLE_DEBUG_LOADER){var b=goog.moduleLoaderState_;goog.moduleLoaderState_=null;try{goog.debugLoader_.load_(a)}finally{goog.moduleLoaderState_=b}}return null}};goog.requireType=function(a){return{}};goog.basePath="";goog.nullFunction=function(){};
goog.abstractMethod=function(){throw Error("unimplemented abstract method");};goog.addSingletonGetter=function(a){a.instance_=void 0;a.getInstance=function(){if(a.instance_)return a.instance_;goog.DEBUG&&(goog.instantiatedSingletons_[goog.instantiatedSingletons_.length]=a);return a.instance_=new a}};goog.instantiatedSingletons_=[];goog.LOAD_MODULE_USING_EVAL=!0;goog.SEAL_MODULE_EXPORTS=goog.DEBUG;goog.loadedModules_={};goog.DEPENDENCIES_ENABLED=!COMPILED&&goog.ENABLE_DEBUG_LOADER;goog.TRANSPILE="detect";
goog.TRANSPILE_TO_LANGUAGE="";goog.TRANSPILER="transpile.js";goog.hasBadLetScoping=null;goog.useSafari10Workaround=function(){if(null==goog.hasBadLetScoping){try{var a=!eval('"use strict";let x = 1; function f() { return typeof x; };f() == "number";')}catch(b){a=!1}goog.hasBadLetScoping=a}return goog.hasBadLetScoping};goog.workaroundSafari10EvalBug=function(a){return"(function(){"+a+"\n;})();\n"};
goog.loadModule=function(a){var b=goog.moduleLoaderState_;try{goog.moduleLoaderState_={moduleName:"",declareLegacyNamespace:!1,type:goog.ModuleType.GOOG};if(goog.isFunction(a))var c=a.call(void 0,{});else if(goog.isString(a))goog.useSafari10Workaround()&&(a=goog.workaroundSafari10EvalBug(a)),c=goog.loadModuleFromSource_.call(void 0,a);else throw Error("Invalid module definition");var d=goog.moduleLoaderState_.moduleName;if(goog.isString(d)&&d)goog.moduleLoaderState_.declareLegacyNamespace?goog.constructNamespace_(d,
c):goog.SEAL_MODULE_EXPORTS&&Object.seal&&"object"==typeof c&&null!=c&&Object.seal(c),goog.loadedModules_[d]={exports:c,type:goog.ModuleType.GOOG,moduleId:goog.moduleLoaderState_.moduleName};else throw Error('Invalid module name "'+d+'"');}finally{goog.moduleLoaderState_=b}};goog.loadModuleFromSource_=function(a){eval(a);return{}};goog.normalizePath_=function(a){a=a.split("/");for(var b=0;b<a.length;)"."==a[b]?a.splice(b,1):b&&".."==a[b]&&a[b-1]&&".."!=a[b-1]?a.splice(--b,2):b++;return a.join("/")};
goog.loadFileSync_=function(a){if(goog.global.CLOSURE_LOAD_FILE_SYNC)return goog.global.CLOSURE_LOAD_FILE_SYNC(a);try{var b=new goog.global.XMLHttpRequest;b.open("get",a,!1);b.send();return 0==b.status||200==b.status?b.responseText:null}catch(c){return null}};
goog.transpile_=function(a,b,c){var d=goog.global.$jscomp;d||(goog.global.$jscomp=d={});var e=d.transpile;if(!e){var f=goog.basePath+goog.TRANSPILER,g=goog.loadFileSync_(f);if(g){(function(){eval(g+"\n//# sourceURL="+f)}).call(goog.global);if(goog.global.$gwtExport&&goog.global.$gwtExport.$jscomp&&!goog.global.$gwtExport.$jscomp.transpile)throw Error('The transpiler did not properly export the "transpile" method. $gwtExport: '+JSON.stringify(goog.global.$gwtExport));goog.global.$jscomp.transpile=
goog.global.$gwtExport.$jscomp.transpile;d=goog.global.$jscomp;e=d.transpile}}e||(e=d.transpile=function(a,b){goog.logToConsole_(b+" requires transpilation but no transpiler was found.");return a});return e(a,b,c)};
goog.typeOf=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};goog.isNull=function(a){return null===a};goog.isDefAndNotNull=function(a){return null!=a};goog.isArray=function(a){return"array"==goog.typeOf(a)};goog.isArrayLike=function(a){var b=goog.typeOf(a);return"array"==b||"object"==b&&"number"==typeof a.length};goog.isDateLike=function(a){return goog.isObject(a)&&"function"==typeof a.getFullYear};goog.isFunction=function(a){return"function"==goog.typeOf(a)};
goog.isObject=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};goog.getUid=function(a){return a[goog.UID_PROPERTY_]||(a[goog.UID_PROPERTY_]=++goog.uidCounter_)};goog.hasUid=function(a){return!!a[goog.UID_PROPERTY_]};goog.removeUid=function(a){null!==a&&"removeAttribute"in a&&a.removeAttribute(goog.UID_PROPERTY_);try{delete a[goog.UID_PROPERTY_]}catch(b){}};goog.UID_PROPERTY_="closure_uid_"+(1E9*Math.random()>>>0);goog.uidCounter_=0;goog.getHashCode=goog.getUid;
goog.removeHashCode=goog.removeUid;goog.cloneObject=function(a){var b=goog.typeOf(a);if("object"==b||"array"==b){if("function"===typeof a.clone)return a.clone();b="array"==b?[]:{};for(var c in a)b[c]=goog.cloneObject(a[c]);return b}return a};goog.bindNative_=function(a,b,c){return a.call.apply(a.bind,arguments)};
goog.bindJs_=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};goog.bind=function(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?goog.bind=goog.bindNative_:goog.bind=goog.bindJs_;return goog.bind.apply(null,arguments)};
goog.partial=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};goog.mixin=function(a,b){for(var c in b)a[c]=b[c]};goog.now=goog.TRUSTED_SITE&&Date.now||function(){return+new Date};
goog.globalEval=function(a){if(goog.global.execScript)goog.global.execScript(a,"JavaScript");else if(goog.global.eval){if(null==goog.evalWorksForGlobals_){try{goog.global.eval("var _evalTest_ = 1;")}catch(d){}if("undefined"!=typeof goog.global._evalTest_){try{delete goog.global._evalTest_}catch(d){}goog.evalWorksForGlobals_=!0}else goog.evalWorksForGlobals_=!1}if(goog.evalWorksForGlobals_)goog.global.eval(a);else{var b=goog.global.document,c=b.createElement("SCRIPT");c.type="text/javascript";c.defer=
!1;c.appendChild(b.createTextNode(a));b.head.appendChild(c);b.head.removeChild(c)}}else throw Error("goog.globalEval not available");};goog.evalWorksForGlobals_=null;
goog.getCssName=function(a,b){if("."==String(a).charAt(0))throw Error('className passed in goog.getCssName must not start with ".". You passed: '+a);var c=function(a){return goog.cssNameMapping_[a]||a},d=function(a){a=a.split("-");for(var b=[],d=0;d<a.length;d++)b.push(c(a[d]));return b.join("-")};d=goog.cssNameMapping_?"BY_WHOLE"==goog.cssNameMappingStyle_?c:d:function(a){return a};a=b?a+"-"+d(b):d(a);return goog.global.CLOSURE_CSS_NAME_MAP_FN?goog.global.CLOSURE_CSS_NAME_MAP_FN(a):a};
goog.setCssNameMapping=function(a,b){goog.cssNameMapping_=a;goog.cssNameMappingStyle_=b};!COMPILED&&goog.global.CLOSURE_CSS_NAME_MAPPING&&(goog.cssNameMapping_=goog.global.CLOSURE_CSS_NAME_MAPPING);goog.getMsg=function(a,b){b&&(a=a.replace(/\{\$([^}]+)}/g,function(a,d){return null!=b&&d in b?b[d]:a}));return a};goog.getMsgWithFallback=function(a,b){return a};goog.exportSymbol=function(a,b,c){goog.exportPath_(a,b,c)};goog.exportProperty=function(a,b,c){a[b]=c};
goog.inherits=function(a,b){function c(){}c.prototype=b.prototype;a.superClass_=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.base=function(a,c,f){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};
goog.base=function(a,b,c){var d=arguments.callee.caller;if(goog.STRICT_MODE_COMPATIBLE||goog.DEBUG&&!d)throw Error("arguments.caller not defined.  goog.base() cannot be used with strict mode code. See http://www.ecma-international.org/ecma-262/5.1/#sec-C");if("undefined"!==typeof d.superClass_){for(var e=Array(arguments.length-1),f=1;f<arguments.length;f++)e[f-1]=arguments[f];return d.superClass_.constructor.apply(a,e)}if("string"!=typeof b&&"symbol"!=typeof b)throw Error("method names provided to goog.base must be a string or a symbol");
e=Array(arguments.length-2);for(f=2;f<arguments.length;f++)e[f-2]=arguments[f];f=!1;for(var g=a.constructor;g;g=g.superClass_&&g.superClass_.constructor)if(g.prototype[b]===d)f=!0;else if(f)return g.prototype[b].apply(a,e);if(a[b]===d)return a.constructor.prototype[b].apply(a,e);throw Error("goog.base called from a method of one name to a method of a different name");};goog.scope=function(a){if(goog.isInModuleLoader_())throw Error("goog.scope is not supported within a module.");a.call(goog.global)};
COMPILED||(goog.global.COMPILED=COMPILED);goog.defineClass=function(a,b){var c=b.constructor,d=b.statics;c&&c!=Object.prototype.constructor||(c=function(){throw Error("cannot instantiate an interface (no constructor defined).");});c=goog.defineClass.createSealingConstructor_(c,a);a&&goog.inherits(c,a);delete b.constructor;delete b.statics;goog.defineClass.applyProperties_(c.prototype,b);null!=d&&(d instanceof Function?d(c):goog.defineClass.applyProperties_(c,d));return c};
goog.defineClass.SEAL_CLASS_INSTANCES=goog.DEBUG;goog.defineClass.createSealingConstructor_=function(a,b){if(!goog.defineClass.SEAL_CLASS_INSTANCES)return a;var c=!goog.defineClass.isUnsealable_(b),d=function(){var b=a.apply(this,arguments)||this;b[goog.UID_PROPERTY_]=b[goog.UID_PROPERTY_];this.constructor===d&&c&&Object.seal instanceof Function&&Object.seal(b);return b};return d};goog.defineClass.isUnsealable_=function(a){return a&&a.prototype&&a.prototype[goog.UNSEALABLE_CONSTRUCTOR_PROPERTY_]};
goog.defineClass.OBJECT_PROTOTYPE_FIELDS_="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");goog.defineClass.applyProperties_=function(a,b){for(var c in b)Object.prototype.hasOwnProperty.call(b,c)&&(a[c]=b[c]);for(var d=0;d<goog.defineClass.OBJECT_PROTOTYPE_FIELDS_.length;d++)c=goog.defineClass.OBJECT_PROTOTYPE_FIELDS_[d],Object.prototype.hasOwnProperty.call(b,c)&&(a[c]=b[c])};
goog.tagUnsealableClass=function(a){!COMPILED&&goog.defineClass.SEAL_CLASS_INSTANCES&&(a.prototype[goog.UNSEALABLE_CONSTRUCTOR_PROPERTY_]=!0)};goog.UNSEALABLE_CONSTRUCTOR_PROPERTY_="goog_defineClass_legacy_unsealable";
!COMPILED&&goog.DEPENDENCIES_ENABLED&&(goog.inHtmlDocument_=function(){var a=goog.global.document;return null!=a&&"write"in a},goog.isDocumentLoading_=function(){var a=goog.global.document;return a.attachEvent?"complete"!=a.readyState:"loading"==a.readyState},goog.findBasePath_=function(){if(goog.isDef(goog.global.CLOSURE_BASE_PATH)&&goog.isString(goog.global.CLOSURE_BASE_PATH))goog.basePath=goog.global.CLOSURE_BASE_PATH;else if(goog.inHtmlDocument_()){var a=goog.global.document,b=a.currentScript;
a=b?[b]:a.getElementsByTagName("SCRIPT");for(b=a.length-1;0<=b;--b){var c=a[b].src,d=c.lastIndexOf("?");d=-1==d?c.length:d;if("base.js"==c.substr(d-7,7)){goog.basePath=c.substr(0,d-7);break}}}},goog.findBasePath_(),goog.Transpiler=function(){this.requiresTranspilation_=null;this.transpilationTarget_=goog.TRANSPILE_TO_LANGUAGE},goog.Transpiler.prototype.createRequiresTranspilation_=function(){function a(a,b){e?d[a]=!0:b()?(c=a,d[a]=!1):e=d[a]=!0}function b(a){try{return!!eval(a)}catch(k){return!1}}
var c="es3",d={es3:!1},e=!1,f=goog.global.navigator&&goog.global.navigator.userAgent?goog.global.navigator.userAgent:"";a("es5",function(){return b("[1,].length==1")});a("es6",function(){var a=f.match(/Edge\/(\d+)(\.\d)*/i);return a&&15>Number(a[1])?!1:b('(()=>{"use strict";class X{constructor(){if(new.target!=String)throw 1;this.x=42}}let q=Reflect.construct(X,[],String);if(q.x!=42||!(q instanceof String))throw 1;for(const a of[2,3]){if(a==2)continue;function f(z={a}){let a=0;return z.a}{function f(){return 0;}}return f()==3}})()')});
a("es6-impl",function(){return!0});a("es7",function(){return b("2 ** 2 == 4")});a("es8",function(){return b("async () => 1, true")});a("es9",function(){return b("({...rest} = {}), true")});a("es_next",function(){return!1});return{target:c,map:d}},goog.Transpiler.prototype.needsTranspile=function(a,b){if("always"==goog.TRANSPILE)return!0;if("never"==goog.TRANSPILE)return!1;if(!this.requiresTranspilation_){var c=this.createRequiresTranspilation_();this.requiresTranspilation_=c.map;this.transpilationTarget_=
this.transpilationTarget_||c.target}if(a in this.requiresTranspilation_)return this.requiresTranspilation_[a]?!0:!goog.inHtmlDocument_()||"es6"!=b||"noModule"in goog.global.document.createElement("script")?!1:!0;throw Error("Unknown language mode: "+a);},goog.Transpiler.prototype.transpile=function(a,b){return goog.transpile_(a,b,this.transpilationTarget_)},goog.transpiler_=new goog.Transpiler,goog.protectScriptTag_=function(a){return a.replace(/<\/(SCRIPT)/ig,"\\x3c/$1")},goog.DebugLoader_=function(){this.dependencies_=
{};this.idToPath_={};this.written_={};this.loadingDeps_=[];this.depsToLoad_=[];this.paused_=!1;this.factory_=new goog.DependencyFactory(goog.transpiler_);this.deferredCallbacks_={};this.deferredQueue_=[]},goog.DebugLoader_.prototype.bootstrap=function(a,b){function c(){d&&(goog.global.setTimeout(d,0),d=null)}var d=b;if(a.length){b=[];for(var e=0;e<a.length;e++){var f=this.getPathFromDeps_(a[e]);if(!f)throw Error("Unregonized namespace: "+a[e]);b.push(this.dependencies_[f])}f=goog.require;var g=0;
for(e=0;e<a.length;e++)f(a[e]),b[e].onLoad(function(){++g==a.length&&c()})}else c()},goog.DebugLoader_.prototype.loadClosureDeps=function(){this.depsToLoad_.push(this.factory_.createDependency(goog.normalizePath_(goog.basePath+"deps.js"),"deps.js",[],[],{},!1));this.loadDeps_()},goog.DebugLoader_.prototype.requested=function(a,b){(a=this.getPathFromDeps_(a))&&(b||this.areDepsLoaded_(this.dependencies_[a].requires))&&(b=this.deferredCallbacks_[a])&&(delete this.deferredCallbacks_[a],b())},goog.DebugLoader_.prototype.setDependencyFactory=
function(a){this.factory_=a},goog.DebugLoader_.prototype.load_=function(a){if(this.getPathFromDeps_(a)){var b=this,c=[],d=function(a){var e=b.getPathFromDeps_(a);if(!e)throw Error("Bad dependency path or symbol: "+a);if(!b.written_[e]){b.written_[e]=!0;a=b.dependencies_[e];for(e=0;e<a.requires.length;e++)goog.isProvided_(a.requires[e])||d(a.requires[e]);c.push(a)}};d(a);a=!!this.depsToLoad_.length;this.depsToLoad_=this.depsToLoad_.concat(c);this.paused_||a||this.loadDeps_()}else throw a="goog.require could not find: "+
a,goog.logToConsole_(a),Error(a);},goog.DebugLoader_.prototype.loadDeps_=function(){for(var a=this,b=this.paused_;this.depsToLoad_.length&&!b;)(function(){var c=!1,d=a.depsToLoad_.shift(),e=!1;a.loading_(d);var f={pause:function(){if(c)throw Error("Cannot call pause after the call to load.");b=!0},resume:function(){c?a.resume_():b=!1},loaded:function(){if(e)throw Error("Double call to loaded.");e=!0;a.loaded_(d)},pending:function(){for(var b=[],c=0;c<a.loadingDeps_.length;c++)b.push(a.loadingDeps_[c]);
return b},setModuleState:function(a){goog.moduleLoaderState_={type:a,moduleName:"",declareLegacyNamespace:!1}},registerEs6ModuleExports:function(a,b,c){c&&(goog.loadedModules_[c]={exports:b,type:goog.ModuleType.ES6,moduleId:c||""})},registerGoogModuleExports:function(a,b){goog.loadedModules_[a]={exports:b,type:goog.ModuleType.GOOG,moduleId:a}},clearModuleState:function(){goog.moduleLoaderState_=null},defer:function(b){if(c)throw Error("Cannot register with defer after the call to load.");a.defer_(d,
b)},areDepsLoaded:function(){return a.areDepsLoaded_(d.requires)}};try{d.load(f)}finally{c=!0}})();b&&this.pause_()},goog.DebugLoader_.prototype.pause_=function(){this.paused_=!0},goog.DebugLoader_.prototype.resume_=function(){this.paused_&&(this.paused_=!1,this.loadDeps_())},goog.DebugLoader_.prototype.loading_=function(a){this.loadingDeps_.push(a)},goog.DebugLoader_.prototype.loaded_=function(a){for(var b=0;b<this.loadingDeps_.length;b++)if(this.loadingDeps_[b]==a){this.loadingDeps_.splice(b,1);
break}for(b=0;b<this.deferredQueue_.length;b++)if(this.deferredQueue_[b]==a.path){this.deferredQueue_.splice(b,1);break}if(this.loadingDeps_.length==this.deferredQueue_.length&&!this.depsToLoad_.length)for(;this.deferredQueue_.length;)this.requested(this.deferredQueue_.shift(),!0);a.loaded()},goog.DebugLoader_.prototype.areDepsLoaded_=function(a){for(var b=0;b<a.length;b++){var c=this.getPathFromDeps_(a[b]);if(!c||!(c in this.deferredCallbacks_||goog.isProvided_(a[b])))return!1}return!0},goog.DebugLoader_.prototype.getPathFromDeps_=
function(a){return a in this.idToPath_?this.idToPath_[a]:a in this.dependencies_?a:null},goog.DebugLoader_.prototype.defer_=function(a,b){this.deferredCallbacks_[a.path]=b;this.deferredQueue_.push(a.path)},goog.LoadController=function(){},goog.LoadController.prototype.pause=function(){},goog.LoadController.prototype.resume=function(){},goog.LoadController.prototype.loaded=function(){},goog.LoadController.prototype.pending=function(){},goog.LoadController.prototype.registerEs6ModuleExports=function(a,
b,c){},goog.LoadController.prototype.setModuleState=function(a){},goog.LoadController.prototype.clearModuleState=function(){},goog.LoadController.prototype.defer=function(a){},goog.LoadController.prototype.areDepsLoaded=function(){},goog.Dependency=function(a,b,c,d,e){this.path=a;this.relativePath=b;this.provides=c;this.requires=d;this.loadFlags=e;this.loaded_=!1;this.loadCallbacks_=[]},goog.Dependency.prototype.getPathName=function(){var a=this.path,b=a.indexOf("://");0<=b&&(a=a.substring(b+3),b=
a.indexOf("/"),0<=b&&(a=a.substring(b+1)));return a},goog.Dependency.prototype.onLoad=function(a){this.loaded_?a():this.loadCallbacks_.push(a)},goog.Dependency.prototype.loaded=function(){this.loaded_=!0;var a=this.loadCallbacks_;this.loadCallbacks_=[];for(var b=0;b<a.length;b++)a[b]()},goog.Dependency.defer_=!1,goog.Dependency.callbackMap_={},goog.Dependency.registerCallback_=function(a){var b=Math.random().toString(32);goog.Dependency.callbackMap_[b]=a;return b},goog.Dependency.unregisterCallback_=
function(a){delete goog.Dependency.callbackMap_[a]},goog.Dependency.callback_=function(a,b){if(a in goog.Dependency.callbackMap_){for(var c=goog.Dependency.callbackMap_[a],d=[],e=1;e<arguments.length;e++)d.push(arguments[e]);c.apply(void 0,d)}else throw Error("Callback key "+a+" does not exist (was base.js loaded more than once?).");},goog.Dependency.prototype.load=function(a){if(goog.global.CLOSURE_IMPORT_SCRIPT)goog.global.CLOSURE_IMPORT_SCRIPT(this.path)?a.loaded():a.pause();else if(goog.inHtmlDocument_()){var b=
goog.global.document;if("complete"==b.readyState&&!goog.ENABLE_CHROME_APP_SAFE_SCRIPT_LOADING){if(/\bdeps.js$/.test(this.path)){a.loaded();return}throw Error('Cannot write "'+this.path+'" after document load');}if(!goog.ENABLE_CHROME_APP_SAFE_SCRIPT_LOADING&&goog.isDocumentLoading_()){var c=goog.Dependency.registerCallback_(function(b){goog.DebugLoader_.IS_OLD_IE_&&"complete"!=b.readyState||(goog.Dependency.unregisterCallback_(c),a.loaded())}),d=!goog.DebugLoader_.IS_OLD_IE_&&goog.getScriptNonce()?
' nonce="'+goog.getScriptNonce()+'"':"";b.write('<script src="'+this.path+'" '+(goog.DebugLoader_.IS_OLD_IE_?"onreadystatechange":"onload")+"=\"goog.Dependency.callback_('"+c+'\', this)" type="text/javascript" '+(goog.Dependency.defer_?"defer":"")+d+">\x3c/script>")}else{var e=b.createElement("script");e.defer=goog.Dependency.defer_;e.async=!1;e.type="text/javascript";(d=goog.getScriptNonce())&&e.setAttribute("nonce",d);goog.DebugLoader_.IS_OLD_IE_?(a.pause(),e.onreadystatechange=function(){if("loaded"==
e.readyState||"complete"==e.readyState)a.loaded(),a.resume()}):e.onload=function(){e.onload=null;a.loaded()};e.src=this.path;b.head.appendChild(e)}}else goog.logToConsole_("Cannot use default debug loader outside of HTML documents."),"deps.js"==this.relativePath?(goog.logToConsole_("Consider setting CLOSURE_IMPORT_SCRIPT before loading base.js, or setting CLOSURE_NO_DEPS to true."),a.loaded()):a.pause()},goog.Es6ModuleDependency=function(a,b,c,d,e){goog.Dependency.call(this,a,b,c,d,e)},goog.inherits(goog.Es6ModuleDependency,
goog.Dependency),goog.Es6ModuleDependency.prototype.load=function(a){function b(a,b){b?d.write('<script type="module" crossorigin>'+b+"\x3c/script>"):d.write('<script type="module" crossorigin src="'+a+'">\x3c/script>')}function c(a,b){var c=d.createElement("script");c.defer=!0;c.async=!1;c.type="module";c.setAttribute("crossorigin",!0);var e=goog.getScriptNonce();e&&c.setAttribute("nonce",e);b?c.textContent=b:c.src=a;d.head.appendChild(c)}if(goog.global.CLOSURE_IMPORT_SCRIPT)goog.global.CLOSURE_IMPORT_SCRIPT(this.path)?
a.loaded():a.pause();else if(goog.inHtmlDocument_()){var d=goog.global.document,e=this;if(goog.isDocumentLoading_()){var f=b;goog.Dependency.defer_=!0}else f=c;var g=goog.Dependency.registerCallback_(function(){goog.Dependency.unregisterCallback_(g);a.setModuleState(goog.ModuleType.ES6)});f(void 0,'goog.Dependency.callback_("'+g+'")');f(this.path,void 0);var k=goog.Dependency.registerCallback_(function(b){goog.Dependency.unregisterCallback_(k);a.registerEs6ModuleExports(e.path,b,goog.moduleLoaderState_.moduleName)});
f(void 0,'import * as m from "'+this.path+'"; goog.Dependency.callback_("'+k+'", m)');var h=goog.Dependency.registerCallback_(function(){goog.Dependency.unregisterCallback_(h);a.clearModuleState();a.loaded()});f(void 0,'goog.Dependency.callback_("'+h+'")')}else goog.logToConsole_("Cannot use default debug loader outside of HTML documents."),a.pause()},goog.TransformedDependency=function(a,b,c,d,e){goog.Dependency.call(this,a,b,c,d,e);this.contents_=null;this.lazyFetch_=!goog.inHtmlDocument_()||!("noModule"in
goog.global.document.createElement("script"))},goog.inherits(goog.TransformedDependency,goog.Dependency),goog.TransformedDependency.prototype.load=function(a){function b(){e.contents_=goog.loadFileSync_(e.path);e.contents_&&(e.contents_=e.transform(e.contents_),e.contents_&&(e.contents_+="\n//# sourceURL="+e.path))}function c(){e.lazyFetch_&&b();if(e.contents_){f&&a.setModuleState(goog.ModuleType.ES6);try{var c=e.contents_;e.contents_=null;goog.globalEval(c);if(f)var d=goog.moduleLoaderState_.moduleName}finally{f&&
a.clearModuleState()}f&&goog.global.$jscomp.require.ensure([e.getPathName()],function(){a.registerEs6ModuleExports(e.path,goog.global.$jscomp.require(e.getPathName()),d)});a.loaded()}}function d(){var a=goog.global.document,b=goog.Dependency.registerCallback_(function(){goog.Dependency.unregisterCallback_(b);c()});a.write('<script type="text/javascript">'+goog.protectScriptTag_('goog.Dependency.callback_("'+b+'");')+"\x3c/script>")}var e=this;if(goog.global.CLOSURE_IMPORT_SCRIPT)b(),this.contents_&&
goog.global.CLOSURE_IMPORT_SCRIPT("",this.contents_)?(this.contents_=null,a.loaded()):a.pause();else{var f=this.loadFlags.module==goog.ModuleType.ES6;this.lazyFetch_||b();var g=1<a.pending().length,k=g&&goog.DebugLoader_.IS_OLD_IE_;g=goog.Dependency.defer_&&(g||goog.isDocumentLoading_());if(k||g)a.defer(function(){c()});else{var h=goog.global.document;k=goog.inHtmlDocument_()&&"ActiveXObject"in goog.global;if(f&&goog.inHtmlDocument_()&&goog.isDocumentLoading_()&&!k){goog.Dependency.defer_=!0;a.pause();
var l=h.onreadystatechange;h.onreadystatechange=function(){"interactive"==h.readyState&&(h.onreadystatechange=l,c(),a.resume());goog.isFunction(l)&&l.apply(void 0,arguments)}}else!goog.DebugLoader_.IS_OLD_IE_&&goog.inHtmlDocument_()&&goog.isDocumentLoading_()?d():c()}}},goog.TransformedDependency.prototype.transform=function(a){},goog.TranspiledDependency=function(a,b,c,d,e,f){goog.TransformedDependency.call(this,a,b,c,d,e);this.transpiler=f},goog.inherits(goog.TranspiledDependency,goog.TransformedDependency),
goog.TranspiledDependency.prototype.transform=function(a){return this.transpiler.transpile(a,this.getPathName())},goog.GoogModuleDependency=function(a,b,c,d,e,f,g){goog.TransformedDependency.call(this,a,b,c,d,e);this.needsTranspile_=f;this.transpiler_=g},goog.inherits(goog.GoogModuleDependency,goog.TransformedDependency),goog.GoogModuleDependency.prototype.transform=function(a){this.needsTranspile_&&(a=this.transpiler_.transpile(a,this.getPathName()));return goog.LOAD_MODULE_USING_EVAL&&goog.isDef(goog.global.JSON)?
"goog.loadModule("+goog.global.JSON.stringify(a+"\n//# sourceURL="+this.path+"\n")+");":'goog.loadModule(function(exports) {"use strict";'+a+"\n;return exports});\n//# sourceURL="+this.path+"\n"},goog.DebugLoader_.IS_OLD_IE_=!(goog.global.atob||!goog.global.document||!goog.global.document.all),goog.DebugLoader_.prototype.addDependency=function(a,b,c,d){b=b||[];a=a.replace(/\\/g,"/");var e=goog.normalizePath_(goog.basePath+a);d&&"boolean"!==typeof d||(d=d?{module:goog.ModuleType.GOOG}:{});c=this.factory_.createDependency(e,
a,b,c,d,goog.transpiler_.needsTranspile(d.lang||"es3",d.module));this.dependencies_[e]=c;for(c=0;c<b.length;c++)this.idToPath_[b[c]]=e;this.idToPath_[a]=e},goog.DependencyFactory=function(a){this.transpiler=a},goog.DependencyFactory.prototype.createDependency=function(a,b,c,d,e,f){return e.module==goog.ModuleType.GOOG?new goog.GoogModuleDependency(a,b,c,d,e,f,this.transpiler):f?new goog.TranspiledDependency(a,b,c,d,e,this.transpiler):e.module==goog.ModuleType.ES6?new goog.Es6ModuleDependency(a,b,
c,d,e):new goog.Dependency(a,b,c,d,e)},goog.debugLoader_=new goog.DebugLoader_,goog.loadClosureDeps=function(){goog.debugLoader_.loadClosureDeps()},goog.setDependencyFactory=function(a){goog.debugLoader_.setDependencyFactory(a)},goog.global.CLOSURE_NO_DEPS||goog.debugLoader_.loadClosureDeps(),goog.bootstrap=function(a,b){goog.debugLoader_.bootstrap(a,b)});goog.dom={};goog.dom.HtmlElement=function(){};goog.dom.TagName=function(a){this.tagName_=a};goog.dom.TagName.prototype.toString=function(){return this.tagName_};goog.dom.TagName.A=new goog.dom.TagName("A");goog.dom.TagName.ABBR=new goog.dom.TagName("ABBR");goog.dom.TagName.ACRONYM=new goog.dom.TagName("ACRONYM");goog.dom.TagName.ADDRESS=new goog.dom.TagName("ADDRESS");goog.dom.TagName.APPLET=new goog.dom.TagName("APPLET");goog.dom.TagName.AREA=new goog.dom.TagName("AREA");goog.dom.TagName.ARTICLE=new goog.dom.TagName("ARTICLE");
goog.dom.TagName.ASIDE=new goog.dom.TagName("ASIDE");goog.dom.TagName.AUDIO=new goog.dom.TagName("AUDIO");goog.dom.TagName.B=new goog.dom.TagName("B");goog.dom.TagName.BASE=new goog.dom.TagName("BASE");goog.dom.TagName.BASEFONT=new goog.dom.TagName("BASEFONT");goog.dom.TagName.BDI=new goog.dom.TagName("BDI");goog.dom.TagName.BDO=new goog.dom.TagName("BDO");goog.dom.TagName.BIG=new goog.dom.TagName("BIG");goog.dom.TagName.BLOCKQUOTE=new goog.dom.TagName("BLOCKQUOTE");goog.dom.TagName.BODY=new goog.dom.TagName("BODY");
goog.dom.TagName.BR=new goog.dom.TagName("BR");goog.dom.TagName.BUTTON=new goog.dom.TagName("BUTTON");goog.dom.TagName.CANVAS=new goog.dom.TagName("CANVAS");goog.dom.TagName.CAPTION=new goog.dom.TagName("CAPTION");goog.dom.TagName.CENTER=new goog.dom.TagName("CENTER");goog.dom.TagName.CITE=new goog.dom.TagName("CITE");goog.dom.TagName.CODE=new goog.dom.TagName("CODE");goog.dom.TagName.COL=new goog.dom.TagName("COL");goog.dom.TagName.COLGROUP=new goog.dom.TagName("COLGROUP");
goog.dom.TagName.COMMAND=new goog.dom.TagName("COMMAND");goog.dom.TagName.DATA=new goog.dom.TagName("DATA");goog.dom.TagName.DATALIST=new goog.dom.TagName("DATALIST");goog.dom.TagName.DD=new goog.dom.TagName("DD");goog.dom.TagName.DEL=new goog.dom.TagName("DEL");goog.dom.TagName.DETAILS=new goog.dom.TagName("DETAILS");goog.dom.TagName.DFN=new goog.dom.TagName("DFN");goog.dom.TagName.DIALOG=new goog.dom.TagName("DIALOG");goog.dom.TagName.DIR=new goog.dom.TagName("DIR");goog.dom.TagName.DIV=new goog.dom.TagName("DIV");
goog.dom.TagName.DL=new goog.dom.TagName("DL");goog.dom.TagName.DT=new goog.dom.TagName("DT");goog.dom.TagName.EM=new goog.dom.TagName("EM");goog.dom.TagName.EMBED=new goog.dom.TagName("EMBED");goog.dom.TagName.FIELDSET=new goog.dom.TagName("FIELDSET");goog.dom.TagName.FIGCAPTION=new goog.dom.TagName("FIGCAPTION");goog.dom.TagName.FIGURE=new goog.dom.TagName("FIGURE");goog.dom.TagName.FONT=new goog.dom.TagName("FONT");goog.dom.TagName.FOOTER=new goog.dom.TagName("FOOTER");goog.dom.TagName.FORM=new goog.dom.TagName("FORM");
goog.dom.TagName.FRAME=new goog.dom.TagName("FRAME");goog.dom.TagName.FRAMESET=new goog.dom.TagName("FRAMESET");goog.dom.TagName.H1=new goog.dom.TagName("H1");goog.dom.TagName.H2=new goog.dom.TagName("H2");goog.dom.TagName.H3=new goog.dom.TagName("H3");goog.dom.TagName.H4=new goog.dom.TagName("H4");goog.dom.TagName.H5=new goog.dom.TagName("H5");goog.dom.TagName.H6=new goog.dom.TagName("H6");goog.dom.TagName.HEAD=new goog.dom.TagName("HEAD");goog.dom.TagName.HEADER=new goog.dom.TagName("HEADER");
goog.dom.TagName.HGROUP=new goog.dom.TagName("HGROUP");goog.dom.TagName.HR=new goog.dom.TagName("HR");goog.dom.TagName.HTML=new goog.dom.TagName("HTML");goog.dom.TagName.I=new goog.dom.TagName("I");goog.dom.TagName.IFRAME=new goog.dom.TagName("IFRAME");goog.dom.TagName.IMG=new goog.dom.TagName("IMG");goog.dom.TagName.INPUT=new goog.dom.TagName("INPUT");goog.dom.TagName.INS=new goog.dom.TagName("INS");goog.dom.TagName.ISINDEX=new goog.dom.TagName("ISINDEX");goog.dom.TagName.KBD=new goog.dom.TagName("KBD");
goog.dom.TagName.KEYGEN=new goog.dom.TagName("KEYGEN");goog.dom.TagName.LABEL=new goog.dom.TagName("LABEL");goog.dom.TagName.LEGEND=new goog.dom.TagName("LEGEND");goog.dom.TagName.LI=new goog.dom.TagName("LI");goog.dom.TagName.LINK=new goog.dom.TagName("LINK");goog.dom.TagName.MAIN=new goog.dom.TagName("MAIN");goog.dom.TagName.MAP=new goog.dom.TagName("MAP");goog.dom.TagName.MARK=new goog.dom.TagName("MARK");goog.dom.TagName.MATH=new goog.dom.TagName("MATH");goog.dom.TagName.MENU=new goog.dom.TagName("MENU");
goog.dom.TagName.MENUITEM=new goog.dom.TagName("MENUITEM");goog.dom.TagName.META=new goog.dom.TagName("META");goog.dom.TagName.METER=new goog.dom.TagName("METER");goog.dom.TagName.NAV=new goog.dom.TagName("NAV");goog.dom.TagName.NOFRAMES=new goog.dom.TagName("NOFRAMES");goog.dom.TagName.NOSCRIPT=new goog.dom.TagName("NOSCRIPT");goog.dom.TagName.OBJECT=new goog.dom.TagName("OBJECT");goog.dom.TagName.OL=new goog.dom.TagName("OL");goog.dom.TagName.OPTGROUP=new goog.dom.TagName("OPTGROUP");
goog.dom.TagName.OPTION=new goog.dom.TagName("OPTION");goog.dom.TagName.OUTPUT=new goog.dom.TagName("OUTPUT");goog.dom.TagName.P=new goog.dom.TagName("P");goog.dom.TagName.PARAM=new goog.dom.TagName("PARAM");goog.dom.TagName.PICTURE=new goog.dom.TagName("PICTURE");goog.dom.TagName.PRE=new goog.dom.TagName("PRE");goog.dom.TagName.PROGRESS=new goog.dom.TagName("PROGRESS");goog.dom.TagName.Q=new goog.dom.TagName("Q");goog.dom.TagName.RP=new goog.dom.TagName("RP");goog.dom.TagName.RT=new goog.dom.TagName("RT");
goog.dom.TagName.RTC=new goog.dom.TagName("RTC");goog.dom.TagName.RUBY=new goog.dom.TagName("RUBY");goog.dom.TagName.S=new goog.dom.TagName("S");goog.dom.TagName.SAMP=new goog.dom.TagName("SAMP");goog.dom.TagName.SCRIPT=new goog.dom.TagName("SCRIPT");goog.dom.TagName.SECTION=new goog.dom.TagName("SECTION");goog.dom.TagName.SELECT=new goog.dom.TagName("SELECT");goog.dom.TagName.SMALL=new goog.dom.TagName("SMALL");goog.dom.TagName.SOURCE=new goog.dom.TagName("SOURCE");goog.dom.TagName.SPAN=new goog.dom.TagName("SPAN");
goog.dom.TagName.STRIKE=new goog.dom.TagName("STRIKE");goog.dom.TagName.STRONG=new goog.dom.TagName("STRONG");goog.dom.TagName.STYLE=new goog.dom.TagName("STYLE");goog.dom.TagName.SUB=new goog.dom.TagName("SUB");goog.dom.TagName.SUMMARY=new goog.dom.TagName("SUMMARY");goog.dom.TagName.SUP=new goog.dom.TagName("SUP");goog.dom.TagName.SVG=new goog.dom.TagName("SVG");goog.dom.TagName.TABLE=new goog.dom.TagName("TABLE");goog.dom.TagName.TBODY=new goog.dom.TagName("TBODY");goog.dom.TagName.TD=new goog.dom.TagName("TD");
goog.dom.TagName.TEMPLATE=new goog.dom.TagName("TEMPLATE");goog.dom.TagName.TEXTAREA=new goog.dom.TagName("TEXTAREA");goog.dom.TagName.TFOOT=new goog.dom.TagName("TFOOT");goog.dom.TagName.TH=new goog.dom.TagName("TH");goog.dom.TagName.THEAD=new goog.dom.TagName("THEAD");goog.dom.TagName.TIME=new goog.dom.TagName("TIME");goog.dom.TagName.TITLE=new goog.dom.TagName("TITLE");goog.dom.TagName.TR=new goog.dom.TagName("TR");goog.dom.TagName.TRACK=new goog.dom.TagName("TRACK");goog.dom.TagName.TT=new goog.dom.TagName("TT");
goog.dom.TagName.U=new goog.dom.TagName("U");goog.dom.TagName.UL=new goog.dom.TagName("UL");goog.dom.TagName.VAR=new goog.dom.TagName("VAR");goog.dom.TagName.VIDEO=new goog.dom.TagName("VIDEO");goog.dom.TagName.WBR=new goog.dom.TagName("WBR");var jsaction={Attribute:{JSACTION:"jsaction",JSNAMESPACE:"jsnamespace",OI:"oi",VED:"ved",VET:"vet",JSINSTANCE:"jsinstance",JSTRACK:"jstrack"},Branch:{MAIN:"main-actionflow-branch"},Char:{NAMESPACE_ACTION_SEPARATOR:".",EVENT_ACTION_SEPARATOR:":",OI_SEPARATOR:".",CAD_KEY_VALUE_SEPARATOR:":",CAD_SEPARATOR:","},EventType:{CLICK:"click",CLICKMOD:"clickmod",CLICKONLY:"clickonly",DBLCLICK:"dblclick",FOCUS:"focus",FOCUSIN:"focusin",BLUR:"blur",FOCUSOUT:"focusout",SUBMIT:"submit",KEYDOWN:"keydown",KEYPRESS:"keypress",
KEYUP:"keyup",MOUSEUP:"mouseup",MOUSEDOWN:"mousedown",MOUSEOVER:"mouseover",MOUSEOUT:"mouseout",MOUSEENTER:"mouseenter",MOUSELEAVE:"mouseleave",MOUSEMOVE:"mousemove",ERROR:"error",LOAD:"load",UNLOAD:"unload",TOUCHSTART:"touchstart",TOUCHEND:"touchend",TOUCHMOVE:"touchmove",INPUT:"input",SCROLL:"scroll",CUSTOM:"_custom"},KeyCodes:{MAC_ENTER:3,ENTER:13,SPACE:32},TagName:{TEXTAREA:"TEXTAREA",INPUT:"INPUT",BUTTON:"BUTTON",A:"A"},Name:{START:"start",CAD:"cad",DUP:"dup"},Tick:{IMP0:"imp0",IMP1:"imp1"},
Property:{JSACTION:"__jsaction",JSNAMESPACE:"__jsnamespace",OI:"__oi",OWNER:"__owner"},UrlParam:{CLICK_TYPE:"ct",CLICK_DATA:"cd",CLICK_ADDITIONAL_DATA:"cad",EVENT_ID:"ei",VISUAL_ELEMENT_CLICK:"ved",VISUAL_ELEMENT_TYPE:"vet"}};jsaction.Cache={};jsaction.Cache.parseCache_={};jsaction.Cache.get=function(a){return a[jsaction.Property.JSACTION]};jsaction.Cache.set=function(a,b){a[jsaction.Property.JSACTION]=b};jsaction.Cache.getParsed=function(a){return jsaction.Cache.parseCache_[a]};jsaction.Cache.setParsed=function(a,b){jsaction.Cache.parseCache_[a]=b};jsaction.Cache.clear=function(a){jsaction.Property.JSACTION in a&&delete a[jsaction.Property.JSACTION]};jsaction.Cache.getNamespace=function(a){return a[jsaction.Property.JSNAMESPACE]};
jsaction.Cache.setNamespace=function(a,b){a[jsaction.Property.JSNAMESPACE]=b};jsaction.Cache.clearNamespace=function(a){jsaction.Property.JSNAMESPACE in a&&delete a[jsaction.Property.JSNAMESPACE]};goog.debug={};goog.debug.Error=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,goog.debug.Error);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a));this.reportErrorToServer=!0};goog.inherits(goog.debug.Error,Error);goog.debug.Error.prototype.name="CustomError";goog.dom.NodeType={ELEMENT:1,ATTRIBUTE:2,TEXT:3,CDATA_SECTION:4,ENTITY_REFERENCE:5,ENTITY:6,PROCESSING_INSTRUCTION:7,COMMENT:8,DOCUMENT:9,DOCUMENT_TYPE:10,DOCUMENT_FRAGMENT:11,NOTATION:12};goog.asserts={};goog.asserts.ENABLE_ASSERTS=goog.DEBUG;goog.asserts.AssertionError=function(a,b){goog.debug.Error.call(this,goog.asserts.subs_(a,b));this.messagePattern=a};goog.inherits(goog.asserts.AssertionError,goog.debug.Error);goog.asserts.AssertionError.prototype.name="AssertionError";goog.asserts.DEFAULT_ERROR_HANDLER=function(a){throw a;};goog.asserts.errorHandler_=goog.asserts.DEFAULT_ERROR_HANDLER;
goog.asserts.subs_=function(a,b){a=a.split("%s");for(var c="",d=a.length-1,e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");return c+a[d]};goog.asserts.doAssertFailure_=function(a,b,c,d){var e="Assertion failed";if(c){e+=": "+c;var f=d}else a&&(e+=": "+a,f=b);a=new goog.asserts.AssertionError(""+e,f||[]);goog.asserts.errorHandler_(a)};goog.asserts.setErrorHandler=function(a){goog.asserts.ENABLE_ASSERTS&&(goog.asserts.errorHandler_=a)};
goog.asserts.assert=function(a,b,c){goog.asserts.ENABLE_ASSERTS&&!a&&goog.asserts.doAssertFailure_("",null,b,Array.prototype.slice.call(arguments,2));return a};goog.asserts.fail=function(a,b){goog.asserts.ENABLE_ASSERTS&&goog.asserts.errorHandler_(new goog.asserts.AssertionError("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1)))};
goog.asserts.assertNumber=function(a,b,c){goog.asserts.ENABLE_ASSERTS&&!goog.isNumber(a)&&goog.asserts.doAssertFailure_("Expected number but got %s: %s.",[goog.typeOf(a),a],b,Array.prototype.slice.call(arguments,2));return a};goog.asserts.assertString=function(a,b,c){goog.asserts.ENABLE_ASSERTS&&!goog.isString(a)&&goog.asserts.doAssertFailure_("Expected string but got %s: %s.",[goog.typeOf(a),a],b,Array.prototype.slice.call(arguments,2));return a};
goog.asserts.assertFunction=function(a,b,c){goog.asserts.ENABLE_ASSERTS&&!goog.isFunction(a)&&goog.asserts.doAssertFailure_("Expected function but got %s: %s.",[goog.typeOf(a),a],b,Array.prototype.slice.call(arguments,2));return a};goog.asserts.assertObject=function(a,b,c){goog.asserts.ENABLE_ASSERTS&&!goog.isObject(a)&&goog.asserts.doAssertFailure_("Expected object but got %s: %s.",[goog.typeOf(a),a],b,Array.prototype.slice.call(arguments,2));return a};
goog.asserts.assertArray=function(a,b,c){goog.asserts.ENABLE_ASSERTS&&!goog.isArray(a)&&goog.asserts.doAssertFailure_("Expected array but got %s: %s.",[goog.typeOf(a),a],b,Array.prototype.slice.call(arguments,2));return a};goog.asserts.assertBoolean=function(a,b,c){goog.asserts.ENABLE_ASSERTS&&!goog.isBoolean(a)&&goog.asserts.doAssertFailure_("Expected boolean but got %s: %s.",[goog.typeOf(a),a],b,Array.prototype.slice.call(arguments,2));return a};
goog.asserts.assertElement=function(a,b,c){!goog.asserts.ENABLE_ASSERTS||goog.isObject(a)&&a.nodeType==goog.dom.NodeType.ELEMENT||goog.asserts.doAssertFailure_("Expected Element but got %s: %s.",[goog.typeOf(a),a],b,Array.prototype.slice.call(arguments,2));return a};
goog.asserts.assertInstanceof=function(a,b,c,d){!goog.asserts.ENABLE_ASSERTS||a instanceof b||goog.asserts.doAssertFailure_("Expected instanceof %s but got %s.",[goog.asserts.getType_(b),goog.asserts.getType_(a)],c,Array.prototype.slice.call(arguments,3));return a};goog.asserts.assertFinite=function(a,b,c){!goog.asserts.ENABLE_ASSERTS||"number"==typeof a&&isFinite(a)||goog.asserts.doAssertFailure_("Expected %s to be a finite number but it is not.",[a],b,Array.prototype.slice.call(arguments,2));return a};
goog.asserts.assertObjectPrototypeIsIntact=function(){for(var a in Object.prototype)goog.asserts.fail(a+" should not be enumerable in Object.prototype.")};goog.asserts.getType_=function(a){return a instanceof Function?a.displayName||a.name||"unknown type name":a instanceof Object?a.constructor.displayName||a.constructor.name||Object.prototype.toString.call(a):null===a?"null":typeof a};goog.functions={};goog.functions.constant=function(a){return function(){return a}};goog.functions.FALSE=function(){return!1};goog.functions.TRUE=function(){return!0};goog.functions.NULL=function(){return null};goog.functions.identity=function(a,b){return a};goog.functions.error=function(a){return function(){throw Error(a);}};goog.functions.fail=function(a){return function(){throw a;}};
goog.functions.lock=function(a,b){b=b||0;return function(){return a.apply(this,Array.prototype.slice.call(arguments,0,b))}};goog.functions.nth=function(a){return function(){return arguments[a]}};goog.functions.partialRight=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.push.apply(b,c);return a.apply(this,b)}};goog.functions.withReturnValue=function(a,b){return goog.functions.sequence(a,goog.functions.constant(b))};
goog.functions.equalTo=function(a,b){return function(c){return b?a==c:a===c}};goog.functions.compose=function(a,b){var c=arguments,d=c.length;return function(){var a;d&&(a=c[d-1].apply(this,arguments));for(var b=d-2;0<=b;b--)a=c[b].call(this,a);return a}};goog.functions.sequence=function(a){var b=arguments,c=b.length;return function(){for(var a,e=0;e<c;e++)a=b[e].apply(this,arguments);return a}};
goog.functions.and=function(a){var b=arguments,c=b.length;return function(){for(var a=0;a<c;a++)if(!b[a].apply(this,arguments))return!1;return!0}};goog.functions.or=function(a){var b=arguments,c=b.length;return function(){for(var a=0;a<c;a++)if(b[a].apply(this,arguments))return!0;return!1}};goog.functions.not=function(a){return function(){return!a.apply(this,arguments)}};
goog.functions.create=function(a,b){var c=function(){};c.prototype=a.prototype;c=new c;a.apply(c,Array.prototype.slice.call(arguments,1));return c};goog.functions.CACHE_RETURN_VALUE=!0;goog.functions.cacheReturnValue=function(a){var b=!1,c;return function(){if(!goog.functions.CACHE_RETURN_VALUE)return a();b||(c=a(),b=!0);return c}};goog.functions.once=function(a){var b=a;return function(){if(b){var a=b;b=null;a()}}};
goog.functions.debounce=function(a,b,c){var d=0;return function(e){goog.global.clearTimeout(d);var f=arguments;d=goog.global.setTimeout(function(){a.apply(c,f)},b)}};goog.functions.throttle=function(a,b,c){var d=0,e=!1,f=[],g=function(){d=0;e&&(e=!1,k())},k=function(){d=goog.global.setTimeout(g,b);a.apply(c,f)};return function(a){f=arguments;d?e=!0:k()}};goog.functions.rateLimit=function(a,b,c){var d=0,e=function(){d=0};return function(f){d||(d=goog.global.setTimeout(e,b),a.apply(c,arguments))}};jsaction.dom={};jsaction.dom.contains=function(a,b){if(goog.isNull(b))return!1;if("contains"in a&&1==b.nodeType)return a.contains(b);if("compareDocumentPosition"in a)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};jsaction.dom.hasAncestorInNodeList=function(a,b){for(var c=0;c<b.length;++c){var d=b[c];if(d!=a&&jsaction.dom.contains(d,a))return!0}return!1};jsaction.createCustomEvent=function(a,b,c){a={_type:a,type:a,data:b,triggeringEvent:c};try{var d=document.createEvent("CustomEvent");d.initCustomEvent(jsaction.EventType.CUSTOM,!0,!1,a)}catch(e){d=document.createEvent("HTMLEvents"),d.initEvent(jsaction.EventType.CUSTOM,!0,!1),d.detail=a}return d};jsaction.fireCustomEvent=function(a,b,c,d){b=jsaction.createCustomEvent(b,c,d);a.dispatchEvent(b)};
jsaction.broadcastCustomEvent=function(a,b,c){goog.asserts.assert("click"!=b);a=a.querySelectorAll('[jsaction^="'+b+':"], [jsaction*=";'+b+':"], [jsaction*=" '+b+':"]');for(var d=0;d<a.length;++d){var e=a[d];jsaction.dom.hasAncestorInNodeList(e,a)||jsaction.fireCustomEvent(e,b,c)}};jsaction.event={};
jsaction.event.addEventListener=function(a,b,c){var d=!1;b==jsaction.EventType.MOUSEENTER?b=jsaction.EventType.MOUSEOVER:b==jsaction.EventType.MOUSELEAVE&&(b=jsaction.EventType.MOUSEOUT);if(a.addEventListener){if(b==jsaction.EventType.FOCUS||b==jsaction.EventType.BLUR||b==jsaction.EventType.ERROR||b==jsaction.EventType.LOAD)d=!0;a.addEventListener(b,c,d)}else a.attachEvent&&(b==jsaction.EventType.FOCUS?b=jsaction.EventType.FOCUSIN:b==jsaction.EventType.BLUR&&(b=jsaction.EventType.FOCUSOUT),c=jsaction.event.attachEventAdapter_(a,
c),a.attachEvent("on"+b,c));return{eventType:b,handler:c,capture:d}};jsaction.event.attachEventAdapter_=function(a,b){return function(c){c||(c=window.event);return b.call(a,c)}};jsaction.event.removeEventListener=function(a,b){a.removeEventListener?a.removeEventListener(b.eventType,b.handler,b.capture):a.detachEvent&&a.detachEvent("on"+b.eventType,b.handler)};jsaction.event.stopPropagation=function(a){a.stopPropagation?a.stopPropagation():a.cancelBubble=!0};
jsaction.event.preventDefault=function(a){a.preventDefault?a.preventDefault():a.returnValue=!1};jsaction.event.getTarget=function(a){a=a.target||a.srcElement;!a.getAttribute&&a.parentNode&&(a=a.parentNode);return a};jsaction.event.isMac_="undefined"!=typeof navigator&&/Macintosh/.test(navigator.userAgent);jsaction.event.isMiddleClick_=function(a){return 2==a.which||null==a.which&&4==a.button};
jsaction.event.isModifiedClickEvent=function(a){return jsaction.event.isMac_&&a.metaKey||!jsaction.event.isMac_&&a.ctrlKey||jsaction.event.isMiddleClick_(a)||a.shiftKey};jsaction.event.isWebKit="undefined"!=typeof navigator&&!/Opera/.test(navigator.userAgent)&&/WebKit/.test(navigator.userAgent);jsaction.event.isSafari="undefined"!=typeof navigator&&/WebKit/.test(navigator.userAgent)&&/Safari/.test(navigator.userAgent);
jsaction.event.isIe="undefined"!=typeof navigator&&(/MSIE/.test(navigator.userAgent)||/Trident/.test(navigator.userAgent));jsaction.event.isGecko="undefined"!=typeof navigator&&!/Opera|WebKit/.test(navigator.userAgent)&&/Gecko/.test(navigator.product);jsaction.event.isValidActionKeyTarget_=function(a){if(!("getAttribute"in a))return!1;var b=(a.getAttribute("role")||a.tagName).toUpperCase();return!jsaction.event.isTextControl_(a)&&("COMBOBOX"!=b||"INPUT"!=b)&&!a.isContentEditable};
jsaction.event.hasModifierKey_=function(a){return a.ctrlKey||a.shiftKey||a.altKey||a.metaKey};jsaction.event.shouldCallPreventDefaultOnNativeHtmlControl=function(a){a=jsaction.event.getTarget(a);var b=(a.getAttribute("role")||a.tagName).toUpperCase();return jsaction.event.isNativeHTMLControl(a)&&"A"!=b&&!jsaction.event.processSpace_(a)&&!jsaction.event.isTextControl_(a)||"BUTTON"==b};
jsaction.event.isActionKeyEvent=function(a){var b=a.which||a.keyCode||a.key;jsaction.event.isWebKit&&b==jsaction.KeyCodes.MAC_ENTER&&(b=jsaction.KeyCodes.ENTER);if(b!=jsaction.KeyCodes.ENTER&&b!=jsaction.KeyCodes.SPACE)return!1;var c=jsaction.event.getTarget(a),d=(c.getAttribute("role")||c.type||c.tagName).toUpperCase();if(a.type!=jsaction.EventType.KEYDOWN||!jsaction.event.isValidActionKeyTarget_(c)||jsaction.event.hasModifierKey_(a)||jsaction.event.processSpace_(c)&&b==jsaction.KeyCodes.SPACE||
!jsaction.event.isFocusable_(c))return!1;a="INPUT"!=c.tagName.toUpperCase()||c.type;c=!(d in jsaction.event.IDENTIFIER_TO_KEY_TRIGGER_MAPPING)&&b==jsaction.KeyCodes.ENTER;return(0==jsaction.event.IDENTIFIER_TO_KEY_TRIGGER_MAPPING[d]%b||c)&&!!a};jsaction.event.isFocusable_=function(a){return(a.tagName in jsaction.event.NATIVELY_FOCUSABLE_ELEMENTS_||jsaction.event.hasSpecifiedTabIndex_(a))&&!a.disabled};
jsaction.event.hasSpecifiedTabIndex_=function(a){a=a.getAttributeNode("tabindex");return goog.isDefAndNotNull(a)&&a.specified};jsaction.event.NATIVELY_FOCUSABLE_ELEMENTS_={A:1,INPUT:1,TEXTAREA:1,SELECT:1,BUTTON:1};jsaction.event.isSpaceKeyEvent=function(a){var b=a.which||a.keyCode||a.key;a=jsaction.event.getTarget(a);a=(a.type||a.tagName).toUpperCase();return b==jsaction.KeyCodes.SPACE&&"CHECKBOX"!=a};
jsaction.event.isMouseSpecialEvent=function(a,b,c){var d=a.relatedTarget;return(a.type==jsaction.EventType.MOUSEOVER&&b==jsaction.EventType.MOUSEENTER||a.type==jsaction.EventType.MOUSEOUT&&b==jsaction.EventType.MOUSELEAVE)&&(!d||d!==c&&!jsaction.dom.contains(c,d))};
jsaction.event.createMouseSpecialEvent=function(a,b){var c={},d;for(d in a)"function"!==typeof a[d]&&"srcElement"!==d&&"target"!==d&&(c[d]=a[d]);c.type=a.type==jsaction.EventType.MOUSEOVER?jsaction.EventType.MOUSEENTER:jsaction.EventType.MOUSELEAVE;c.target=c.srcElement=b;c.bubbles=!1;return c};jsaction.event.getTouchData=function(a){return(a=a.changedTouches&&a.changedTouches[0]||a.touches&&a.touches[0])?{clientX:a.clientX,clientY:a.clientY,screenX:a.screenX,screenY:a.screenY}:null};
jsaction.event.recreateTouchEventAsClick=function(a){var b={};b.originalEventType=a.type;b.type=jsaction.EventType.CLICK;for(var c in a){var d=a[c];"type"==c||"srcElement"==c||goog.isFunction(d)||(b[c]=d)}b.timeStamp=goog.now();b.defaultPrevented=!1;b.preventDefault=jsaction.event.syntheticPreventDefault_;b._propagationStopped=!1;b.stopPropagation=jsaction.event.syntheticStopPropagation_;if(a=jsaction.event.getTouchData(a))b.clientX=a.clientX,b.clientY=a.clientY,b.screenX=a.screenX,b.screenY=a.screenY;
return b};jsaction.event.isMouseEventsPrevented=function(a){return!!a._mouseEventsPrevented};jsaction.event.preventMouseEvents=function(a){a._mouseEventsPrevented=!0};jsaction.event.syntheticPreventMouseEvents_=function(){jsaction.event.preventMouseEvents(this)};jsaction.event.addPreventMouseEventsSupport=function(a){a._preventMouseEvents=jsaction.event.syntheticPreventMouseEvents_};jsaction.event.syntheticPreventDefault_=function(){this.defaultPrevented=!0};
jsaction.event.syntheticStopPropagation_=function(){this._propagationStopped=!0};jsaction.event.maybeCopyEvent=function(a){var b=goog.global.document;if(b&&!b.createEvent&&b.createEventObject)try{return b.createEventObject(a)}catch(c){return a}else return a};
jsaction.event.IDENTIFIER_TO_KEY_TRIGGER_MAPPING={A:jsaction.KeyCodes.ENTER,BUTTON:0,CHECKBOX:jsaction.KeyCodes.SPACE,COMBOBOX:jsaction.KeyCodes.ENTER,GRIDCELL:jsaction.KeyCodes.ENTER,LINK:jsaction.KeyCodes.ENTER,LISTBOX:jsaction.KeyCodes.ENTER,MENU:0,MENUBAR:0,MENUITEM:0,MENUITEMCHECKBOX:0,MENUITEMRADIO:0,OPTION:0,RADIO:jsaction.KeyCodes.SPACE,RADIOGROUP:jsaction.KeyCodes.SPACE,RESET:0,SUBMIT:0,TAB:0,TREE:jsaction.KeyCodes.ENTER,TREEITEM:jsaction.KeyCodes.ENTER};
jsaction.event.processSpace_=function(a){return(a.getAttribute("type")||a.tagName).toUpperCase()in jsaction.event.PROCESS_SPACE_};jsaction.event.isTextControl_=function(a){return(a.getAttribute("type")||a.tagName).toUpperCase()in jsaction.event.TEXT_CONTROLS_};jsaction.event.isNativeHTMLControl=function(a){return a.tagName.toUpperCase()in jsaction.event.NATIVE_HTML_CONTROLS_};jsaction.event.PROCESS_SPACE_={CHECKBOX:!0,OPTION:!0,RADIO:!0};
jsaction.event.TEXT_CONTROLS_={COLOR:!0,DATE:!0,DATETIME:!0,"DATETIME-LOCAL":!0,EMAIL:!0,MONTH:!0,NUMBER:!0,PASSWORD:!0,RANGE:!0,SEARCH:!0,TEL:!0,TEXT:!0,TEXTAREA:!0,TIME:!0,URL:!0,WEEK:!0};jsaction.event.NATIVE_HTML_CONTROLS_={A:!0,AREA:!0,BUTTON:!0,DIALOG:!0,IMG:!0,INPUT:!0,LINK:!0,MENU:!0,OPTGROUP:!0,OPTION:!0,PROGRESS:!0,SELECT:!0,TEXTAREA:!0};jsaction.replayEvent=function(a){var b=jsaction.createEvent(a.event,a.eventType);jsaction.triggerEvent(a.targetElement,b)};jsaction.isKeyboardEvent_=function(a){return a==jsaction.EventType.KEYPRESS||a==jsaction.EventType.KEYDOWN||a==jsaction.EventType.KEYUP};jsaction.isMouseEvent_=function(a){return a==jsaction.EventType.CLICK||a==jsaction.EventType.DBLCLICK||a==jsaction.EventType.MOUSEDOWN||a==jsaction.EventType.MOUSEOVER||a==jsaction.EventType.MOUSEOUT||a==jsaction.EventType.MOUSEMOVE};
jsaction.isUiEvent_=function(a){return a==jsaction.EventType.FOCUS||a==jsaction.EventType.BLUR||a==jsaction.EventType.FOCUSIN||a==jsaction.EventType.FOCUSOUT||a==jsaction.EventType.SCROLL};jsaction.createKeyboardModifiersList_=function(a,b,c,d){var e=[];a&&e.push("Alt");b&&e.push("Control");c&&e.push("Meta");d&&e.push("Shift");return e.join(" ")};
jsaction.createUiEvent=function(a,b){if(document.createEvent){var c=document.createEvent("UIEvent");c.initUIEvent(b||a.type,goog.isDef(a.bubbles)?a.bubbles:!0,a.cancelable||!1,a.view||window,a.detail||0)}else goog.asserts.assert(document.createEventObject),c=document.createEventObject(),c.type=b||a.type,c.bubbles=goog.isDef(a.bubbles)?a.bubbles:!0,c.cancelable=a.cancelable||!1,c.view=a.view||window,c.detail=a.detail||0;c.relatedTarget=a.relatedTarget||null;c.originalTimestamp=a.timeStamp;return c};
jsaction.createKeyboardEvent=function(a,b){if(jsaction.event.isSafari){var c=jsaction.createGenericEvent_(a,b);c.ctrlKey=a.ctrlKey;c.altKey=a.altKey;c.shiftKey=a.shiftKey;c.metaKey=a.metaKey;c.keyCode=a.keyCode;c.charCode=a.charCode;c.originalTimestamp=a.timeStamp;return c}if(document.createEvent)if(c=document.createEvent("KeyboardEvent"),c.initKeyboardEvent){var d=jsaction.createKeyboardModifiersList_(a.altKey,a.ctrlKey,a.metaKey,a.shiftKey);c.initKeyboardEvent(b||a.type,!0,!0,window,a.charCode,
a.keyCode,a.location,d,a.repeat,a.locale);if(jsaction.event.isWebKit||jsaction.event.isIe)b=goog.functions.constant(a.keyCode),Object.defineProperty(c,"keyCode",{get:b}),Object.defineProperty(c,"which",{get:b})}else goog.asserts.assert(c.initKeyEvent),c.initKeyEvent(b||a.type,!0,!0,window,a.ctrlKey,a.altKey,a.shiftKey,a.metaKey,a.keyCode,a.charCode);else goog.asserts.assert(document.createEventObject),c=document.createEventObject(),c.type=b||a.type,c.repeat=a.repeat,c.ctrlKey=a.ctrlKey,c.altKey=a.altKey,
c.shiftKey=a.shiftKey,c.metaKey=a.metaKey,c.keyCode=a.keyCode,c.charCode=a.charCode;c.originalTimestamp=a.timeStamp;return c};
jsaction.createMouseEvent=function(a,b){if(document.createEvent){var c=document.createEvent("MouseEvent");c.initMouseEvent(b||a.type,!0,!0,window,a.detail||1,a.screenX||0,a.screenY||0,a.clientX||0,a.clientY||0,a.ctrlKey||!1,a.altKey||!1,a.shiftKey||!1,a.metaKey||!1,a.button||0,a.relatedTarget||null)}else goog.asserts.assert(document.createEventObject),c=document.createEventObject(),c.type=b||a.type,c.clientX=a.clientX,c.clientY=a.clientY,c.button=a.button,c.detail=a.detail,c.ctrlKey=a.ctrlKey,c.altKey=
a.altKey,c.shiftKey=a.shiftKey,c.metaKey=a.metaKey;c.originalTimestamp=a.timeStamp;return c};jsaction.createGenericEvent_=function(a,b){if(document.createEvent){var c=document.createEvent("Event");c.initEvent(b||a.type,!0,!0)}else goog.asserts.assert(document.createEventObject),c=document.createEventObject(),c.type=b||a.type;c.originalTimestamp=a.timeStamp;return c};
jsaction.createEvent=function(a,b){var c=a.type==jsaction.EventType.CUSTOM?jsaction.EventType.CUSTOM:b||a.type;jsaction.isKeyboardEvent_(c)?b=jsaction.createKeyboardEvent(a,b):jsaction.isMouseEvent_(c)?b=jsaction.createMouseEvent(a,b):jsaction.isUiEvent_(c)?b=jsaction.createUiEvent(a,b):c==jsaction.EventType.CUSTOM?(goog.asserts.assert(b),b=jsaction.createCustomEvent(b,a.detail.data,a.detail.triggeringEvent),b.originalTimestamp=a.timeStamp):b=jsaction.createGenericEvent_(a,b);return b};
jsaction.triggerEvent=function(a,b){if(a.dispatchEvent)return a.dispatchEvent(b);goog.asserts.assert(a.fireEvent);return a.fireEvent("on"+b.type,b)};jsaction.domGenerator={};jsaction.domGenerator.Generator=function(){};jsaction.domGenerator.Generator.prototype.next=function(){};jsaction.domGenerator.Ancestors=function(){this.container_=this.node_=null};jsaction.domGenerator.Ancestors.prototype.reset_=function(a,b){this.node_=a;this.container_=b;return this};
jsaction.domGenerator.Ancestors.prototype.next=function(){var a=this.node_;this.node_=this.node_&&this.node_!=this.container_?this.node_[jsaction.Property.OWNER]||this.node_.parentNode:null;return a};jsaction.domGenerator.EventPath=function(){this.path_=[];this.idx_=0;this.container_=null;this.usingAncestors_=!1};jsaction.domGenerator.EventPath.prototype.reset_=function(a,b){this.path_=a;this.idx_=0;this.container_=b;this.usingAncestors_=!1;return this};
jsaction.domGenerator.EventPath.prototype.next=function(){if(this.usingAncestors_)return jsaction.domGenerator.ancestors_.next();if(this.idx_!=this.path_.length){var a=this.path_[this.idx_];this.idx_++;a!=this.container_&&a&&a[jsaction.Property.OWNER]&&(this.usingAncestors_=!0,jsaction.domGenerator.ancestors_.reset_(a[jsaction.Property.OWNER],this.container_));return a}return null};jsaction.domGenerator.ancestors_=new jsaction.domGenerator.Ancestors;jsaction.domGenerator.eventPath_=new jsaction.domGenerator.EventPath;
jsaction.domGenerator.getGenerator=function(a,b,c){return a.path?jsaction.domGenerator.eventPath_.reset_(a.path,c):jsaction.domGenerator.ancestors_.reset_(b,c)};jsaction.EventContract=function(){this.installers_=[];this.containers_=[];this.nestedContainers_=[];this.events_={};this.dispatcher_=null;this.queue_=[];jsaction.EventContract.CUSTOM_EVENT_SUPPORT&&this.addEvent(jsaction.EventType.CUSTOM)};jsaction.EventContract.USE_EVENT_PATH=!1;jsaction.EventContract.isIos_="undefined"!=typeof navigator&&/iPhone|iPad|iPod/.test(navigator.userAgent);jsaction.EventContract.JSNAMESPACE_SUPPORT=!0;jsaction.EventContract.A11Y_CLICK_SUPPORT=!1;
jsaction.EventContract.MOUSE_SPECIAL_SUPPORT=!1;jsaction.EventContract.FAST_CLICK_SUPPORT=!1;jsaction.EventContract.STOP_PROPAGATION=!0;jsaction.EventContract.CUSTOM_EVENT_SUPPORT=!1;jsaction.EventContract.CLICKKEY_="clickkey";jsaction.EventContract.stringTrim_=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^\s+/,"").replace(/\s+$/,"")};jsaction.EventContract.REGEXP_SEMICOLON_=/\s*;\s*/;jsaction.EventContract.defaultEventType_=jsaction.EventType.CLICK;
jsaction.EventContract.preventingMouseEvents_=null;jsaction.EventContract.getDefaultEventType=function(){return jsaction.EventContract.defaultEventType_};jsaction.EventContract.setDefaultEventType=function(a){jsaction.EventContract.defaultEventType_=a};
jsaction.EventContract.eventHandler_=function(a,b){return function(c){var d=b;if(jsaction.EventContract.CUSTOM_EVENT_SUPPORT&&d==jsaction.EventType.CUSTOM){d=c.detail;if(!d||!d._type)return;d=d._type}d=jsaction.EventContract.createEventInfo_(d,c,this);if(a.dispatcher_){var e=jsaction.EventContract.createEventInfoInternal_(d.eventType,d.event,d.targetElement,d.action,d.actionElement,d.timeStamp);e.eventType==jsaction.EventType.CLICKONLY&&(e.eventType=jsaction.EventType.CLICK);a.dispatcher_(e,!0)}d.actionElement&&
(jsaction.EventContract.STOP_PROPAGATION&&(!jsaction.event.isGecko||"INPUT"!=d.targetElement.tagName&&"TEXTAREA"!=d.targetElement.tagName||d.eventType!=jsaction.EventType.FOCUS)&&jsaction.event.stopPropagation(c),"A"!=d.actionElement.tagName||d.eventType!=jsaction.EventType.CLICK&&d.eventType!=jsaction.EventType.CLICKMOD||jsaction.event.preventDefault(c),a.dispatcher_?a.dispatcher_(d):(c=jsaction.event.maybeCopyEvent(c),d.event=c,a.queue_.push(d)),jsaction.EventContract.afterEventHandler_(d))}};
jsaction.EventContract.afterEventHandler_=function(a){a.event.type==jsaction.EventType.TOUCHEND&&jsaction.event.isMouseEventsPrevented(a.event)&&(jsaction.EventContract.preventingMouseEvents_=jsaction.event.recreateTouchEventAsClick(a.event))};
jsaction.EventContract.createEventInfo_=function(a,b,c){a==jsaction.EventType.CLICK&&jsaction.event.isModifiedClickEvent(b)?a=jsaction.EventType.CLICKMOD:jsaction.EventContract.A11Y_CLICK_SUPPORT&&jsaction.event.isActionKeyEvent(b)&&(a=jsaction.EventContract.CLICKKEY_);var d=b.srcElement||b.target,e=jsaction.EventContract.createEventInfoInternal_(a,b,d,"",null);if(jsaction.EventContract.USE_EVENT_PATH)for(var f=jsaction.domGenerator.getGenerator(b,d,c),g;g=f.next();){var k=g;var h=jsaction.EventContract.getAction_(k,
a,b,c);e=jsaction.EventContract.createEventInfoInternal_(h.eventType,h.event||b,d,h.action||"",k,e.timeStamp);if(h.ignore||h.action)break}else{for(g=d;g&&g!=c&&(k=g,h=jsaction.EventContract.getAction_(k,a,b,c),!h.ignore&&!h.action);g=g[jsaction.Property.OWNER]||g.parentNode);h&&(e=jsaction.EventContract.createEventInfoInternal_(h.eventType,h.event||b,d,h.action||"",k,e.timeStamp))}e&&e.eventType==jsaction.EventType.TOUCHEND&&jsaction.event.addPreventMouseEventsSupport(e.event);if(h&&h.action)return jsaction.EventContract.A11Y_CLICK_SUPPORT&&
a==jsaction.EventContract.CLICKKEY_&&(jsaction.event.isSpaceKeyEvent(b)||jsaction.event.shouldCallPreventDefaultOnNativeHtmlControl(b))&&jsaction.event.preventDefault(b),!jsaction.EventContract.MOUSE_SPECIAL_SUPPORT||a!=jsaction.EventType.MOUSEENTER&&a!=jsaction.EventType.MOUSELEAVE||(jsaction.event.isMouseSpecialEvent(b,a,k)?(a=jsaction.event.createMouseSpecialEvent(b,k),e.event=a,e.targetElement=k):(e.action="",e.actionElement=null)),e;e.action="";e.actionElement=null;return e};
jsaction.EventContract.createEventInfoInternal_=function(a,b,c,d,e,f){return{eventType:a,event:b,targetElement:c,action:d,actionElement:e,timeStamp:f||goog.now()}};jsaction.EventContract.getAttr_=function(a,b){var c=null;"getAttribute"in a&&(c=a.getAttribute(b));return c};jsaction.EventContract.EMPTY_ACTION_MAP_={};
jsaction.EventContract.getAction_=function(a,b,c,d){var e=jsaction.Cache.get(a);if(!e){var f=jsaction.EventContract.getAttr_(a,jsaction.Attribute.JSACTION);if(f){e=jsaction.Cache.getParsed(f);if(!e){e={};for(var g=f.split(jsaction.EventContract.REGEXP_SEMICOLON_),k=0,h=g?g.length:0;k<h;k++){var l=g[k];if(l){var n=l.indexOf(jsaction.Char.EVENT_ACTION_SEPARATOR),p=-1!=n,m=p?jsaction.EventContract.stringTrim_(l.substr(0,n)):jsaction.EventContract.defaultEventType_;l=p?jsaction.EventContract.stringTrim_(l.substr(n+
1)):l;e[m]=l}}jsaction.Cache.setParsed(f,e)}if(jsaction.EventContract.JSNAMESPACE_SUPPORT)for(m in f=e,e={},f)e[m]=jsaction.EventContract.getQualifiedName_(f[m],a,d)}else e=jsaction.EventContract.EMPTY_ACTION_MAP_;jsaction.Cache.set(a,e)}jsaction.EventContract.A11Y_CLICK_SUPPORT&&(b==jsaction.EventContract.CLICKKEY_?b=jsaction.EventType.CLICK:b!=jsaction.EventType.CLICK||e[jsaction.EventType.CLICK]||(b=jsaction.EventType.CLICKONLY));d=null;if(jsaction.EventContract.FAST_CLICK_SUPPORT&&e[jsaction.EventType.CLICK]){a=
jsaction.EventContract.getFastClickEvent_(a,c,e);if(!a)return{eventType:b,action:"",event:null,ignore:!0};a!=c&&(d=a,b=a.type)}return{eventType:b,action:e[b]||"",event:d,ignore:!1}};jsaction.EventContract.getQualifiedName_=function(a,b,c){if(jsaction.EventContract.JSNAMESPACE_SUPPORT){if(jsaction.EventContract.isQualifiedName_(a))return a;for(;b;b=b.parentNode){var d=jsaction.EventContract.getNamespace_(b);if(d)return d+jsaction.Char.NAMESPACE_ACTION_SEPARATOR+a;if(b==c)break}}return a};
jsaction.EventContract.getFastClickEvent_=function(a,b,c){if(b.type==jsaction.EventType.CLICK||b.targetTouches&&1<b.targetTouches.length)return b;var d=jsaction.EventContract.fastClickNode_,e=b.target;if(e&&jsaction.EventContract.isInput_(e))return b;e=jsaction.event.getTouchData(b);if(b.type!=jsaction.EventType.TOUCHSTART||c[jsaction.EventType.TOUCHSTART]||c[jsaction.EventType.TOUCHEND])if(b.type==jsaction.EventType.TOUCHEND&&d&&d.node==a)if(b.defaultPrevented||e&&4<Math.abs(e.clientX-d.x)+Math.abs(e.clientY-
d.y))jsaction.EventContract.resetFastClickNode_();else{a=jsaction.event.recreateTouchEventAsClick(b);jsaction.EventContract.preventingMouseEvents_=a;b.stopPropagation();b.preventDefault();b=jsaction.createMouseEvent(a);b._fastclick=!0;a.target.dispatchEvent(b);if(!b.defaultPrevented){if(document.activeElement&&document.activeElement!=b.target&&jsaction.EventContract.isInput_(document.activeElement))try{document.activeElement.blur()}catch(f){}try{window.getSelection().removeAllRanges()}catch(f){}}return null}else b.type==
jsaction.EventType.TOUCHMOVE&&d&&e&&4<Math.abs(e.clientX-d.x)+Math.abs(e.clientY-d.y)&&jsaction.EventContract.resetFastClickNode_();else return jsaction.EventContract.fastClickNode_={node:a,x:e?e.clientX:0,y:e?e.clientY:0},jsaction.EventContract.preventingMouseEvents_=null,clearTimeout(jsaction.EventContract.fastClickTimeout_),jsaction.EventContract.fastClickTimeout_=setTimeout(jsaction.EventContract.resetFastClickNode_,400),null;return b};
jsaction.EventContract.isInput_=function(a){a=a.tagName||"";return"TEXTAREA"==a||"INPUT"==a||"SELECT"==a||"OPTION"==a};jsaction.EventContract.resetFastClickNode_=function(){jsaction.EventContract.fastClickNode_=null};
jsaction.EventContract.sweepupPreventedMouseEvents_=function(a){if(!a._fastclick){var b=jsaction.EventContract.preventingMouseEvents_;if(b)if(800<goog.now()-b.timeStamp)jsaction.EventContract.preventingMouseEvents_=null;else{var c=4>=Math.abs(a.clientX-b.clientX)+Math.abs(a.clientY-b.clientY);b.target==a.target||c?(a.stopPropagation(),a.preventDefault(),a.type==jsaction.EventType.CLICK&&(jsaction.EventContract.preventingMouseEvents_=null)):jsaction.EventContract.preventingMouseEvents_=null}}};
jsaction.EventContract.JSNAMESPACE_SUPPORT&&(jsaction.EventContract.isQualifiedName_=function(a){return 0<=a.indexOf(jsaction.Char.NAMESPACE_ACTION_SEPARATOR)},jsaction.EventContract.getNamespace_=function(a){var b=jsaction.Cache.getNamespace(a);goog.isDef(b)||(b=jsaction.EventContract.getAttr_(a,jsaction.Attribute.JSNAMESPACE),jsaction.Cache.setNamespace(a,b));return b});
jsaction.EventContract.containerHandlerInstaller_=function(a,b){return function(c){return jsaction.event.addEventListener(c,a,b)}};
jsaction.EventContract.prototype.addEvent=function(a,b){if(!this.events_.hasOwnProperty(a)&&(jsaction.EventContract.MOUSE_SPECIAL_SUPPORT||a!=jsaction.EventType.MOUSEENTER&&a!=jsaction.EventType.MOUSELEAVE)){var c=jsaction.EventContract.eventHandler_(this,a);b=jsaction.EventContract.containerHandlerInstaller_(b||a,c);this.events_[a]=c;this.installers_.push(b);for(c=0;c<this.containers_.length;++c)this.containers_[c].installHandler(b);jsaction.EventContract.A11Y_CLICK_SUPPORT&&a==jsaction.EventType.CLICK&&
this.addEvent(jsaction.EventType.KEYDOWN);jsaction.EventContract.FAST_CLICK_SUPPORT&&a==jsaction.EventType.CLICK&&this.initializeFastClick_()}};
jsaction.EventContract.prototype.initializeFastClick_=function(){this.addEvent(jsaction.EventType.TOUCHSTART);this.addEvent(jsaction.EventType.TOUCHEND);this.addEvent(jsaction.EventType.TOUCHMOVE);document.addEventListener&&(document.addEventListener(jsaction.EventType.CLICK,jsaction.EventContract.sweepupPreventedMouseEvents_,!0),document.addEventListener(jsaction.EventType.MOUSEUP,jsaction.EventContract.sweepupPreventedMouseEvents_,!0),document.addEventListener(jsaction.EventType.MOUSEDOWN,jsaction.EventContract.sweepupPreventedMouseEvents_,
!0))};jsaction.EventContract.prototype.handler=function(a){return this.events_[a]};jsaction.EventContract.prototype.addContainer=function(a){var b=new jsaction.EventContractContainer(a);if(jsaction.EventContract.STOP_PROPAGATION)this.setUpContainer_(b),this.containers_.push(b);else{if(this.hasContainerFor_(a))return this.nestedContainers_.push(b),b;this.setUpContainer_(b);this.containers_.push(b);this.updateNestedContainers_()}return b};
jsaction.EventContract.prototype.updateNestedContainers_=function(){for(var a=this.nestedContainers_.concat(this.containers_),b=[],c=[],d=0;d<this.containers_.length;++d){var e=this.containers_[d];jsaction.EventContractContainer.isNested_(e,a)?(b.push(e),e.cleanUp()):c.push(e)}for(d=0;d<this.nestedContainers_.length;++d)e=this.nestedContainers_[d],jsaction.EventContractContainer.isNested_(e,a)?b.push(e):(c.push(e),this.setUpContainer_(e));this.containers_=c;this.nestedContainers_=b};
jsaction.EventContract.prototype.setUpContainer_=function(a){var b=a.div;jsaction.EventContract.isIos_&&(b.style.cursor="pointer");for(b=0;b<this.installers_.length;++b)a.installHandler(this.installers_[b])};jsaction.EventContract.prototype.hasContainerFor_=function(a){for(var b=0;b<this.containers_.length;b++)if(this.containers_[b].containsNode(a))return!0;return!1};
jsaction.EventContract.prototype.removeContainer=function(a){a.cleanUp();for(var b=!1,c=0;c<this.containers_.length;++c)if(this.containers_[c]===a){this.containers_.splice(c,1);b=!0;break}if(!b)for(c=0;c<this.nestedContainers_.length;++c)if(this.nestedContainers_[c]===a){this.nestedContainers_.splice(c,1);break}jsaction.EventContract.STOP_PROPAGATION||this.updateNestedContainers_()};
jsaction.EventContract.prototype.dispatchTo=function(a){this.dispatcher_=a;this.queue_&&(0<this.queue_.length&&a(this.queue_),this.queue_=null)};jsaction.EventContractContainer=function(a){this.div=a;this.handlers_=[]};jsaction.EventContractContainer.prototype.containsNode=function(a){return jsaction.EventContractContainer.containsNode_(this.div,a)};jsaction.EventContractContainer.isNested_=function(a,b){for(var c=0;c<b.length;++c)if(b[c].div!=a.div&&b[c].containsNode(a.div))return!0;return!1};
jsaction.EventContractContainer.containsNode_=function(a,b){for(;a!=b&&b.parentNode;)b=b.parentNode;return a==b};jsaction.EventContractContainer.prototype.installHandler=function(a){this.handlers_.push(a.call(null,this.div))};jsaction.EventContractContainer.prototype.cleanUp=function(){for(var a=0;a<this.handlers_.length;++a)jsaction.event.removeEventListener(this.div,this.handlers_[a]);this.handlers_=[]};jsaction.eventContractAuto={};function bindEventsForContainer(a,b){if(goog.isNull(b))return!1;var c=b.getAttribute("data-jsaction-events");if(!c)return!1;a.addContainer(b);c=c.split(",");b=0;for(var d;d=c[b++];)a.addEvent(d);return!0}function main(a){a.jsaction={EventContract:jsaction.EventContract}}main(goog.global);})();
